# # Dataflow
steps:
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: mvn
  args:
    - compile
    - exec:java
    - -Dexec.mainClass=org.apache.beam.examples.WordCount
    - "-Dexec.args=--project=niveustraining --region=asia-south1 --runner=DataflowRunner --gcpTempLocation=//dataflow-apache-quickstart_niveustraining/temp/ --stagingLocation=gs://techtest-2/staging/ --network=aa-psrk-lan-trusted --subnetwork=https://www.googleapis.com/compute/v1/projects/niveustraining/regions/asia-south1/subnetworks/psrk-trusted" 
